repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
        args: ["-C", "./api"]
      - id: poetry-lock
        args: ["-C", "./api"]
      - id: poetry-check
        args: ["-C", "./db"]
      - id: poetry-lock
        args: ["-C", "./db"]
      - id: poetry-check
        args: ["-C", "./airtable"]
      - id: poetry-lock
        args: ["-C", "./airtable"]
      - id: poetry-check
        args: ["-C", "./utils"]
      - id: poetry-lock
        args: ["-C", "./utils"]
      - id: poetry-export
        args: ["-C", "./api", "-f", "requirements.txt", "-o", "./api/requirements.txt"]
      - id: poetry-check
      - id: poetry-lock

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.9.0'
  #   hooks:
  #     - id: mypy
