services:
    db:
        platform: linux/amd64
        container_name: db
        restart: always
        healthcheck: 
            interval: 10s
            retries: 10
            test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
            timeout: 2s
        image: timescale/timescaledb-ha:pg17
        ports: 
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data      
        env_file:
            - .env
    
    loggernet:
        container_name: loggernet
        build: ./mbx-networks/loggernet
        restart: always
        ports:
            - 6788:6789
            - 8080:8080
            - 5678:5678
        volumes:
            - ln-data:/var/opt/CampbellSci/LoggerNet/data
            - ${LN_SOFTWARE}:/opt/ln
            - ./mbx-networks/loggernet:/app
        environment:
            - LN_VERSION=${LN_VERSION}
            - APP_MODE=debug

volumes: 
    db-data: {}
    ln-data: {}