version: '3.9'

services:
    db:
        # platform: linux/arm64/v8
        container_name: db
        restart: always
        image: timescale/timescaledb:latest-pg16
        ports: 
            - "5432:5432"
        networks:
            - web
        volumes:
            - db-data:/var/lib/postgresql/data      
        env_file:
            - .env

networks:
    web:
        external: true

volumes: 
    db-data: 