version: '3.9'

services:
    db:
        platform: linux/amd64
        container_name: db
        restart: always
        healthcheck:
            test: "exit 0"
        image: timescale/timescaledb-ha:pg16
        ports: 
            - "5432:5432"
        networks:
            - web
        volumes:
            - db-data:/var/lib/postgresql/data      
        env_file:
            - .env
    airflow:
        container_name: airflow
        image: apache/airflow:latest-python3.11
        ports:
            - "8080:8080"
        

networks:
    web:
        external: true

volumes: 
    db-data: 